version: "3.3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
  e2e:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm test
